#!/bin/bash

failcount=0

for t in *.test
do
    if ./$t
    then
        result='\e[32mPASS\e[0m'
    else
        result='\e[31mFAIL\e[0m'
        failcount=$(($failcount + 1))
    fi
    printf "%-40s[$result]\n" "$t"
done

echo
echo "$failcount tests failed"
if [ "$failcount" -ne 0 ]
then
    exit 1
fi
